# Generated by Django 2.1.4 on 2018-12-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=250)),
                ('customer_active', models.BooleanField()),
            ],
        ),
    ]
