# Generated by Django 2.1.4 on 2018-12-28 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=250)),
                ('project_active', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracking.Customer')),
            ],
        ),
    ]
