# Generated by Django 2.1.4 on 2018-12-28 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(auto_now=True)),
                ('saved_date', models.DateTimeField(auto_now=True)),
                ('work_load', models.IntegerField()),
                ('tracking_status', models.SmallIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracking.Project')),
            ],
        ),
    ]
